# Site
name: 'Blogger kampret'
description: 'Hi, I am kampret, the author of kampret, Share Tips About Blogger!'
logo: 'assets/images/logo.png'
favicon: 'assets/images/icon.jpeg'
baseurl: '/'
disqus: ''
email: 'Myinbox@my.id'
mailchimp-list: ''

include: ["_pages"]
permalink: :title

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    IDEV:
      name:           IDEV
      site:           
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am kampret, the author of IDEV, Share Tips About Blogger!"
      email:          Myinbox@my.id
      
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
